;;; Automatically generated by `recentf' on Sat Feb 10 15:21:04 2007.

(setq recentf-list
      '(
        "/Users/phred/dev/sl/trunk/tmpl/app/report.tmpl"
        "/Users/phred/.vim/wordlists/perl.list"
        "/Users/phred/emacs/Preferences.el"
        "/Users/phred/emacs/tt-mode.el"
        "/Users/phred/dev/sl/trunk/tmpl/app/right.tmpl"
        "/Users/phred/dev/sl/trunk/tmpl/app/left.tmpl"
        "/Users/phred/dev/sl/trunk/tmpl/app/settings/router.tmpl"
        "/Users/phred/dev/sl/trunk/tmpl/app/ad/edit.tmpl"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Report.pm"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Ad.pm"
        "/Users/phred/dev/sl/trunk/bin/sl_report.pl"
        "/Users/phred/dev/sl/trunk/conf/sl.conf.dev"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/App/Settings.pm"
        "/Users/phred/dev/sl/trunk/conf/sl.conf"
        "/Users/phred/dev/sl/trunk/conf/sl.conf.prod"
        "/Users/phred/dev/sl/trunk/conf/httpd_app.conf"
        "/Users/phred/dev/modperl/mod_perl-2.0/xs/maps/apache2_structures.map"
        "/Users/phred/dev/modperl/mod_perl-2.0/t/response/TestAPI/request_rec.pm"
        "/Users/phred/dev/sl/trunk/tmpl/app/settings/account.tmpl"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/App/Ad.pm"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
