;;; Automatically generated by `recentf' on Wed Feb  7 12:19:27 2007.

(setq recentf-list
      '(
        "/Users/phred/emacs/Preferences.el"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/App/Settings.pm"
        "/Users/phred/dev/modperl/mod_perl-2.0/xs/maps/apache2_structures.map"
        "/Users/phred/dev/modperl/mod_perl-2.0/t/response/TestAPI/request_rec.pm"
        "/Users/phred/.vim/wordlists/perl.list"
        "/Users/phred/dev/sl/trunk/tmpl/app/settings/account.tmpl"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/App/Ad.pm"
        "/Users/phred/dev/sl/trunk/lib/SL/Model.pm"
        "/Users/phred/dev/sl/trunk/bin/sl_update_schema.pl"
        "/System/Library/Perl/5.8.6/perl5db.pl"
        "/Users/phred/dev/sl/trunk/t/02netflix.t"
        "/Applications/Aquamacs Emacs.app/Contents/Resources/etc/DISTRIB"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Ad.pm"
        "/Users/phred/dev/sl/trunk/conf/startup_proxy.pl"
        "/Users/phred/dev/sl/trunk/conf/startup_app.pl"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Subrequest.pm"
        "/Users/phred/dev/sl/trunk/t/lib/LWP/Protocol/http.pm"
        "/Users/phred/dev/sl/trunk/conf/sl.conf.dev"
        "/Users/phred/dev/sl/trunk/conf/sl.conf"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/Proxy/ResponseHandler.pm"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
