;;; Automatically generated by `recentf' on Fri Jan 12 01:45:39 2007.

(setq recentf-list
      '(
        "/Users/phred/dev/sl/trunk/bin/sl_update_schema.pl"
        "/System/Library/Perl/5.8.6/perl5db.pl"
        "/Users/phred/dev/sl/trunk/sql2/func/ad_md5.sql"
        "/Users/phred/dev/sl/trunk/sql2/table/ad.sql"
        "/Users/phred/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/phred/dev/sl/trunk/sql/func/ad_md5.sql"
        "/Users/phred/dev/sl/trunk/sql2/rule/ad.sql"
        "/Users/phred/dev/sl/trunk/bin/sl_update_linkshare.pl"
        "/Users/phred/dev/sl/trunk/sql2/table/ad_linkshare.sql"
        "/Users/phred/dev/sl/trunk/sql2/table/ad_sl.sql"
        "/Users/phred/dev/sl/trunk/bin/insert.pl"
        "/Users/phred/dev/sl/trunk/bin/linksys_configure.pl"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Ad.pm"
        "/Users/phred/dev/sl/trunk/lib/SL/Model/Ad/Group.pm"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/Proxy/ResponseHandler.pm"
        "/Users/phred/dev/sl/trunk/lib/SL/Apache/App.pm"
        "/Users/phred/dev/sl/trunk/conf/sl.conf.dev"
        "/Users/phred/dev/sl/trunk/conf/sl.conf"
        "/Users/phred/foo.txt"
        "/Users/phred/ipt_webstr.c"
        ))

(setq recentf-filter-changer-current 'nil)


;;; Local Variables:
;;; coding: emacs-mule
;;; End:
